language: c

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      osx_image: xcode11

script:
  - cd ${TRAVIS_BUILD_DIR}
  - sh ./build.sh init
  - ./configure
  - FAKETIME_COMPILE_CFLAGS="-DFORCE_MONOTONIC_FIX" make
  - cd test
  - make test
  - make distcheck
