name: Run make test for automake branch

on:
  push:
    branches:
      - automake
  schedule:
    - cron:  '30 9 * * *'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        ref: automake
    - name: init
      run: sh ./build.sh init
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make test
      run: cd test ; make test
